// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _754: x0 => x0.baseURI,
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: x0 => x0.remove(),
      _1294: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1294(f,arguments.length,x0) }),
      _1295: x0 => ({createScriptURL: x0}),
      _1296: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1297: (x0,x1,x2) => x0.createScriptURL(x1,x2),
      _1298: x0 => x0.hasChildNodes(),
      _1299: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _1300: (x0,x1) => x0.append(x1),
      _1301: (x0,x1) => x0.querySelectorAll(x1),
      _1302: (x0,x1) => x0.item(x1),
      _1303: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1304: (x0,x1,x2) => x0.open(x1,x2),
      _1305: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1305(f,arguments.length,x0,x1) }),
      _1306: x0 => globalThis.Sentry.init(x0),
      _1307: () => new Sentry.getClient(),
      _1308: x0 => x0.getOptions(),
      _1312: () => globalThis.Sentry.globalHandlersIntegration(),
      _1313: () => globalThis.Sentry.dedupeIntegration(),
      _1314: () => globalThis.Sentry.close(),
      _1315: (x0,x1) => x0.sendEnvelope(x1),
      _1318: () => globalThis.globalThis,
      _1319: x0 => x0.sdk,
      _1320: (x0,x1) => { x0.sdk = x1 },
      _1321: (x0,x1) => { x0.name = x1 },
      _1322: x0 => ({type: x0}),
      _1323: (x0,x1) => new Blob(x0,x1),
      _1324: x0 => globalThis.URL.createObjectURL(x0),
      _1325: (x0,x1) => x0.getElementById(x1),
      _1326: (x0,x1) => x0.createElement(x1),
      _1327: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _1328: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1329: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1329(f,arguments.length,x0) }),
      _1330: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1331: x0 => x0.click(),
      _1332: () => ({}),
      _1333: x0 => globalThis.pdfjsLib.getDocument(x0),
      _1334: (x0,x1) => x0.getContext(x1),
      _1335: (x0,x1) => x0.getPage(x1),
      _1336: (x0,x1) => x0.getViewport(x1),
      _1337: (x0,x1) => x0.render(x1),
      _1338: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1338(f,arguments.length,x0) }),
      _1339: (x0,x1) => x0.toBlob(x1),
      _1340: () => new FileReader(),
      _1341: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1342: x0 => x0.cleanup(),
      _1343: x0 => x0.destroy(),
      _1344: (x0,x1) => { x0.module = x1 },
      _1345: (x0,x1) => { x0.exports = x1 },
      _1346: x0 => x0.preventDefault(),
      _1347: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1348: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1350: (x0,x1) => x0.getAttribute(x1),
      _1374: (x0,x1) => x0.querySelector(x1),
      _1375: x0 => globalThis.URL.revokeObjectURL(x0),
      _1376: (x0,x1) => x0.write(x1),
      _1377: x0 => x0.close(),
      _1378: x0 => x0.close(),
      _1379: x0 => x0.createReader(),
      _1380: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1380(f,arguments.length,x0) }),
      _1381: (x0,x1) => x0.readEntries(x1),
      _1382: () => new Blob(),
      _1383: (x0,x1,x2,x3) => x0.slice(x1,x2,x3),
      _1384: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1384(f,arguments.length,x0) }),
      _1385: (x0,x1) => x0.file(x1),
      _1386: x0 => x0.webkitGetAsEntry(),
      _1387: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1387(f,arguments.length,x0) }),
      _1388: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1388(f,arguments.length,x0) }),
      _1389: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1389(f,arguments.length,x0) }),
      _1390: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1390(f,arguments.length,x0) }),
      _1392: x0 => x0.decode(),
      _1393: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1394: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1395: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1395(f,arguments.length,x0) }),
      _1396: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1396(f,arguments.length,x0) }),
      _1397: x0 => x0.send(),
      _1398: () => new XMLHttpRequest(),
      _1399: (x0,x1) => x0.getItem(x1),
      _1400: (x0,x1) => x0.removeItem(x1),
      _1401: (x0,x1,x2) => x0.setItem(x1,x2),
      _1402: (x0,x1) => x0.item(x1),
      _1404: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1404(f,arguments.length,x0) }),
      _1405: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1405(f,arguments.length,x0) }),
      _1406: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1406(f,arguments.length,x0) }),
      _1407: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1407(f,arguments.length,x0) }),
      _1408: (x0,x1) => x0.removeChild(x1),
      _1411: (x0,x1) => x0.key(x1),
      _1412: (x0,x1,x2,x3,x4,x5,x6,x7) => x0.unwrapKey(x1,x2,x3,x4,x5,x6,x7),
      _1413: (x0,x1,x2,x3,x4,x5) => x0.importKey(x1,x2,x3,x4,x5),
      _1414: (x0,x1,x2,x3) => x0.generateKey(x1,x2,x3),
      _1415: (x0,x1,x2,x3,x4) => x0.wrapKey(x1,x2,x3,x4),
      _1416: (x0,x1,x2) => x0.exportKey(x1,x2),
      _1417: (x0,x1) => x0.getRandomValues(x1),
      _1418: (x0,x1,x2,x3) => x0.encrypt(x1,x2,x3),
      _1419: (x0,x1,x2,x3) => x0.decrypt(x1,x2,x3),
      _1426: Date.now,
      _1427: secondsSinceEpoch => {
        const date = new Date(secondsSinceEpoch * 1000);
        const match = /\((.*)\)/.exec(date.toString());
        if (match == null) {
            // This should never happen on any recent browser.
            return '';
        }
        return match[1];
      },
      _1428: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1429: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1430: () => new Error().stack,
      _1431: () => typeof dartUseDateNowForTicks !== "undefined",
      _1432: () => 1000 * performance.now(),
      _1433: () => Date.now(),
      _1434: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1435: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1436: () => new WeakMap(),
      _1437: (map, o) => map.get(o),
      _1438: (map, o, v) => map.set(o, v),
      _1439: (exn) => exn.toString(),
      _1440: (exn) => exn.stack,
      _1441: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1442: x0 => new WeakRef(x0),
      _1443: x0 => x0.deref(),
      _1450: () => globalThis.WeakRef,
      _1454: s => JSON.stringify(s),
      _1455: s => printToConsole(s),
      _1456: (o, p, r) => o.replaceAll(p, () => r),
      _1457: (o, p, r) => o.replace(p, () => r),
      _1458: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1459: s => s.toUpperCase(),
      _1460: s => s.trim(),
      _1461: s => s.trimLeft(),
      _1462: s => s.trimRight(),
      _1463: (string, times) => string.repeat(times),
      _1464: Function.prototype.call.bind(String.prototype.indexOf),
      _1465: (s, p, i) => s.lastIndexOf(p, i),
      _1466: (string, token) => string.split(token),
      _1467: Object.is,
      _1471: (o, c) => o instanceof c,
      _1472: o => Object.keys(o),
      _1475: (o, a) => o + a,
      _1502: x0 => new Array(x0),
      _1504: x0 => x0.length,
      _1506: (x0,x1) => x0[x1],
      _1507: (x0,x1,x2) => { x0[x1] = x2 },
      _1510: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1512: x0 => new Int8Array(x0),
      _1513: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1515: x0 => new Uint8ClampedArray(x0),
      _1517: x0 => new Int16Array(x0),
      _1519: x0 => new Uint16Array(x0),
      _1521: x0 => new Int32Array(x0),
      _1523: x0 => new Uint32Array(x0),
      _1525: x0 => new Float32Array(x0),
      _1527: x0 => new Float64Array(x0),
      _1551: x0 => x0.random(),
      _1552: (x0,x1) => x0.getRandomValues(x1),
      _1553: () => globalThis.crypto,
      _1554: () => globalThis.Math,
      _1567: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _1568: (handle) => clearTimeout(handle),
      _1569: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _1570: (handle) => clearInterval(handle),
      _1571: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _1572: () => Date.now(),
      _1573: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _1574: (x0,x1) => x0.exec(x1),
      _1575: (x0,x1) => x0.test(x1),
      _1576: x0 => x0.pop(),
      _1578: o => o === undefined,
      _1580: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _1582: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _1583: o => o instanceof RegExp,
      _1584: (l, r) => l === r,
      _1585: o => o,
      _1586: o => o,
      _1587: o => o,
      _1588: b => !!b,
      _1589: o => o.length,
      _1591: (o, i) => o[i],
      _1592: f => f.dartFunction,
      _1593: () => ({}),
      _1594: () => [],
      _1596: () => globalThis,
      _1597: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _1598: (o, p) => p in o,
      _1599: (o, p) => o[p],
      _1600: (o, p, v) => o[p] = v,
      _1601: (o, m, a) => o[m].apply(o, a),
      _1603: o => String(o),
      _1604: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _1605: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1605(f,arguments.length,x0) }),
      _1606: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1606(f,arguments.length,x0,x1) }),
      _1607: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _1608: o => [o],
      _1609: (o0, o1) => [o0, o1],
      _1610: (o0, o1, o2) => [o0, o1, o2],
      _1611: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _1612: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1613: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1614: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1615: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1616: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1617: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1618: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1619: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1620: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _1621: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _1622: x0 => new ArrayBuffer(x0),
      _1623: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _1625: x0 => x0.index,
      _1626: x0 => x0.groups,
      _1627: x0 => x0.flags,
      _1628: x0 => x0.multiline,
      _1629: x0 => x0.ignoreCase,
      _1630: x0 => x0.unicode,
      _1631: x0 => x0.dotAll,
      _1632: (x0,x1) => { x0.lastIndex = x1 },
      _1633: (o, p) => p in o,
      _1634: (o, p) => o[p],
      _1635: (o, p, v) => o[p] = v,
      _1637: () => new XMLHttpRequest(),
      _1638: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1642: x0 => x0.send(),
      _1644: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1644(f,arguments.length,x0) }),
      _1645: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1645(f,arguments.length,x0) }),
      _1650: (x0,x1) => x0.appendChild(x1),
      _1652: x0 => x0.deviceMemory,
      _1653: (x0,x1) => x0.matchMedia(x1),
      _1654: () => new AbortController(),
      _1655: x0 => x0.abort(),
      _1656: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _1657: (x0,x1) => globalThis.fetch(x0,x1),
      _1658: (x0,x1) => x0.get(x1),
      _1659: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._1659(f,arguments.length,x0,x1,x2) }),
      _1660: (x0,x1) => x0.forEach(x1),
      _1661: x0 => x0.getReader(),
      _1662: x0 => x0.cancel(),
      _1663: x0 => x0.read(),
      _1664: x0 => x0.trustedTypes,
      _1665: (x0,x1) => { x0.src = x1 },
      _1666: (x0,x1) => x0.createScriptURL(x1),
      _1667: x0 => x0.nonce,
      _1668: (x0,x1) => x0.debug(x1),
      _1669: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1669(f,arguments.length,x0) }),
      _1670: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1670(f,arguments.length,x0) }),
      _1671: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1671(f,arguments.length,x0) }),
      _1673: (x0,x1) => { x0.data = x1 },
      _1674: (x0,x1) => { x0.scale = x1 },
      _1675: (x0,x1) => { x0.canvasContext = x1 },
      _1676: (x0,x1) => { x0.viewport = x1 },
      _1677: (x0,x1) => { x0.cMapUrl = x1 },
      _1678: (x0,x1) => { x0.cMapPacked = x1 },
      _1679: x0 => x0.promise,
      _1680: x0 => x0.numPages,
      _1681: x0 => x0.width,
      _1682: x0 => x0.height,
      _1683: x0 => x0.promise,
      _1684: o => o instanceof Array,
      _1685: (a, i) => a.push(i),
      _1686: (a, i) => a.splice(i, 1)[0],
      _1688: (a, l) => a.length = l,
      _1689: a => a.pop(),
      _1690: (a, i) => a.splice(i, 1),
      _1691: (a, s) => a.join(s),
      _1692: (a, s, e) => a.slice(s, e),
      _1694: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _1695: a => a.length,
      _1697: (a, i) => a[i],
      _1698: (a, i, v) => a[i] = v,
      _1700: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _1701: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _1703: o => o instanceof Uint8Array,
      _1704: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _1705: o => o instanceof Int8Array,
      _1706: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _1707: o => o instanceof Uint8ClampedArray,
      _1708: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _1709: o => o instanceof Uint16Array,
      _1710: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _1711: o => o instanceof Int16Array,
      _1712: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _1713: o => o instanceof Uint32Array,
      _1714: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _1715: o => o instanceof Int32Array,
      _1716: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _1718: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _1719: o => o instanceof Float32Array,
      _1720: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _1721: o => o instanceof Float64Array,
      _1722: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _1723: (t, s) => t.set(s),
      _1724: l => new DataView(new ArrayBuffer(l)),
      _1725: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _1726: o => o.byteLength,
      _1727: o => o.buffer,
      _1728: o => o.byteOffset,
      _1729: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _1730: (b, o) => new DataView(b, o),
      _1731: (b, o, l) => new DataView(b, o, l),
      _1732: Function.prototype.call.bind(DataView.prototype.getUint8),
      _1733: Function.prototype.call.bind(DataView.prototype.setUint8),
      _1734: Function.prototype.call.bind(DataView.prototype.getInt8),
      _1735: Function.prototype.call.bind(DataView.prototype.setInt8),
      _1736: Function.prototype.call.bind(DataView.prototype.getUint16),
      _1737: Function.prototype.call.bind(DataView.prototype.setUint16),
      _1738: Function.prototype.call.bind(DataView.prototype.getInt16),
      _1739: Function.prototype.call.bind(DataView.prototype.setInt16),
      _1740: Function.prototype.call.bind(DataView.prototype.getUint32),
      _1741: Function.prototype.call.bind(DataView.prototype.setUint32),
      _1742: Function.prototype.call.bind(DataView.prototype.getInt32),
      _1743: Function.prototype.call.bind(DataView.prototype.setInt32),
      _1746: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _1747: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _1748: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _1749: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _1750: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _1751: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _1752: Function.prototype.call.bind(Number.prototype.toString),
      _1753: Function.prototype.call.bind(BigInt.prototype.toString),
      _1754: Function.prototype.call.bind(Number.prototype.toString),
      _1755: (d, digits) => d.toFixed(digits),
      _1767: () => globalThis.document,
      _1773: (x0,x1) => { x0.height = x1 },
      _1775: (x0,x1) => { x0.width = x1 },
      _1777: (x0,x1) => { x0.pointerEvents = x1 },
      _1786: x0 => x0.style,
      _1789: x0 => x0.src,
      _1790: (x0,x1) => { x0.src = x1 },
      _1791: x0 => x0.naturalWidth,
      _1792: x0 => x0.naturalHeight,
      _1808: x0 => x0.status,
      _1809: (x0,x1) => { x0.responseType = x1 },
      _1811: x0 => x0.response,
      _1888: x0 => { globalThis.onGoogleLibraryLoad = x0 },
      _1889: (module,f) => finalizeWrapper(f, function() { return module.exports._1889(f,arguments.length) }),
      _1938: (x0,x1) => { x0.responseType = x1 },
      _1939: x0 => x0.response,
      _1999: (x0,x1) => { x0.draggable = x1 },
      _2015: x0 => x0.style,
      _2214: (x0,x1) => { x0.nonce = x1 },
      _2372: (x0,x1) => { x0.target = x1 },
      _2374: (x0,x1) => { x0.download = x1 },
      _2399: (x0,x1) => { x0.href = x1 },
      _2944: (x0,x1) => { x0.accept = x1 },
      _2958: x0 => x0.files,
      _2984: (x0,x1) => { x0.multiple = x1 },
      _3002: (x0,x1) => { x0.type = x1 },
      _3252: (x0,x1) => { x0.src = x1 },
      _3254: (x0,x1) => { x0.type = x1 },
      _3258: (x0,x1) => { x0.async = x1 },
      _3260: (x0,x1) => { x0.defer = x1 },
      _3262: (x0,x1) => { x0.crossOrigin = x1 },
      _3266: (x0,x1) => { x0.integrity = x1 },
      _3297: x0 => x0.width,
      _3298: (x0,x1) => { x0.width = x1 },
      _3299: x0 => x0.height,
      _3300: (x0,x1) => { x0.height = x1 },
      _3703: x0 => x0.items,
      _3706: (x0,x1) => x0[x1],
      _3710: x0 => x0.length,
      _3716: x0 => x0.dataTransfer,
      _3720: () => globalThis.window,
      _3758: x0 => x0.document,
      _3761: x0 => x0.location,
      _3780: x0 => x0.navigator,
      _3784: x0 => x0.screen,
      _3796: x0 => x0.devicePixelRatio,
      _3851: (x0,x1) => { x0.ondragenter = x1 },
      _3853: (x0,x1) => { x0.ondragleave = x1 },
      _3855: (x0,x1) => { x0.ondragover = x1 },
      _3859: (x0,x1) => { x0.ondrop = x1 },
      _4035: x0 => x0.isSecureContext,
      _4038: x0 => x0.crypto,
      _4042: x0 => x0.trustedTypes,
      _4043: x0 => x0.sessionStorage,
      _4044: x0 => x0.localStorage,
      _4052: x0 => x0.href,
      _4053: (x0,x1) => { x0.href = x1 },
      _4054: x0 => x0.origin,
      _4063: x0 => x0.pathname,
      _4101: (x0,x1) => { x0.returnValue = x1 },
      _4164: x0 => x0.platform,
      _4167: x0 => x0.userAgent,
      _4168: x0 => x0.vendor,
      _4173: x0 => x0.onLine,
      _4375: x0 => x0.length,
      _4378: x0 => x0.key,
      _4380: x0 => x0.newValue,
      _6279: x0 => x0.type,
      _6320: x0 => x0.signal,
      _6329: x0 => x0.length,
      _6369: x0 => x0.baseURI,
      _6375: x0 => x0.firstChild,
      _6386: () => globalThis.document,
      _6464: x0 => x0.body,
      _6466: x0 => x0.head,
      _6796: (x0,x1) => { x0.id = x1 },
      _6820: (x0,x1) => { x0.innerHTML = x1 },
      _6823: x0 => x0.children,
      _7129: x0 => x0.clientX,
      _7130: x0 => x0.clientY,
      _8142: x0 => x0.value,
      _8144: x0 => x0.done,
      _8324: x0 => x0.size,
      _8325: x0 => x0.type,
      _8331: x0 => x0.name,
      _8332: x0 => x0.lastModified,
      _8337: x0 => x0.length,
      _8342: x0 => x0.result,
      _8839: x0 => x0.url,
      _8841: x0 => x0.status,
      _8843: x0 => x0.statusText,
      _8844: x0 => x0.headers,
      _8845: x0 => x0.body,
      _9112: x0 => x0.type,
      _9127: x0 => x0.matches,
      _9138: x0 => x0.availWidth,
      _9139: x0 => x0.availHeight,
      _9144: x0 => x0.orientation,
      _11249: (x0,x1) => { x0.display = x1 },
      _12471: x0 => x0.name,
      _12475: x0 => x0.subtle,
      _13146: x0 => x0.isDirectory,
      _13147: x0 => x0.name,
      _13148: x0 => x0.fullPath,
      _13178: () => globalThis.console,
      _13203: () => globalThis.window.flutterCanvasKit,
      _13204: () => globalThis.window._flutter_skwasmInstance,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
